### ISSUE TITLE
Bug with sunglasses - can equip then but can not unequip

### ISSUE THREAD

**Issue by royalko** [ESX-Org/esx_accessories#10]
I have in database this field:
{"skin":{"glasses_1":1,"glasses_2":1},"hasGlasses":true}

I can equip them but I can not unequip sunglasses. Mask, Helmet and Ear accessories working but sunglasses no.

**Comment by TemptressTeelia** [comment]
Zero things work for me.

**Comment by aprilkae** [comment]
Same here, everything else works fine except sunglasses.

**Comment by EGUltraTM** [comment]
yep same here

**Comment by ElPumpo** [comment]
Fixed with 2028350a9593c7b7acea1ace34653d6301691b25
