### ISSUE TITLE
Not saving in database.

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_accessories#2]
Why it is not saving the items in database? I buy hat etc but after i leave serwer i lose it.

**Comment by niiK0** [comment]
what u did to fix it? still not working for me, it doesnt store nothing in the database

**Comment by JaroSound** [comment]
Just change the time until the next save in the database.

//Close

**Comment by niiK0** [comment]
Excuse me for continuin the post, i searched the whole script and even in the esx_skin but couldn't find how to change the time until next save, how exactly should i do it?
