### ISSUE TITLE
Set/unset not working

### ISSUE THREAD

**Issue by Sidusol** [ESX-Org/esx_accessories#8]
Under the "k" menu to set/unset accessories when I press any of the options they are not working. The only way to unset mask is to go to shop...

**Comment by royalko** [comment]
same problem here

**Comment by TemptressTeelia** [comment]
Same here

**Comment by ElPumpo** [comment]
Update skinchanger

**Comment by EbenSantuy** [comment]
still cant bro @ElPumpo im already update the skinchanger by you
